# Generated by Django 4.2.15 on 2024-09-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitter', '0002_sitter_service_type_alter_sitter_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter',
            name='email',
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='sitter_id',
            field=models.IntegerField(default=1727424120628444, editable=False, unique=True),
        ),
    ]
