# Generated by Django 4.2.15 on 2024-09-05 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sitter_requester', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitterRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=200, null=True)),
                ('service_type', models.CharField(max_length=100, null=True)),
                ('service_date', models.DateTimeField(auto_now_add=True)),
                ('town', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('attempt_sitter_pair_id', models.CharField(max_length=200)),
                ('paired_sitter_id', models.CharField(max_length=200)),
                ('number_of_pets', models.IntegerField(default=1)),
                ('sitter_requester_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sitter_requester.sitterrequester')),
            ],
        ),
    ]
