# Generated by Django 4.2.15 on 2024-09-24 06:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sitter_requester', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitterRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('service_type', models.CharField(max_length=100, null=True)),
                ('service_date', models.DateTimeField(auto_now_add=True)),
                ('town', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('attempt_sitter_pair_id', models.CharField(max_length=200)),
                ('paired_sitter_id', models.CharField(max_length=200)),
                ('number_of_pets', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Created'), (1, 'Matched'), (2, 'Completed'), (3, 'Canceled')], default=0)),
                ('sitter_requester_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sitter_requester.sitterrequester')),
            ],
        ),
    ]
