# Generated by Django 4.2.15 on 2024-09-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitter_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitterrequest',
            name='service_type',
            field=models.IntegerField(choices=[(0, 'Pet'), (1, 'House')], default=0),
        ),
    ]
