# Generated by Django 4.2.15 on 2024-09-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitter_request', '0002_alter_sitterrequest_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitterrequest',
            name='attempt_sitter_pair_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sitterrequest',
            name='paired_sitter_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
