# Generated by Django 4.2.15 on 2024-09-27 08:20

from django.db import migrations, models
import sitterapi.utils


class Migration(migrations.Migration):

    dependencies = [
        ('sitter_requester', '0003_alter_sitterrequester_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitterrequester',
            name='sitter_requester_id',
            field=models.IntegerField(default=sitterapi.utils.create_id_from_timestamp, editable=False, unique=True),
        ),
    ]
